spring.application.name=service-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/db_rnd
spring.datasource.username=rnd
spring.datasource.password=rnd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000
#custom message
spring.messages.basename=ValidationMessages
spring.messages.encoding=UTF-8
#sftp
sftp.username=dicka
sftp.password=password
sftp.host=127.0.0.1
sftp.port=2222
sftp.folder=upload
sftp.move-folder=history
#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379